# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 144854aeede6d8c9564718a6b928fc2084d3d2cfe682a6a892499628f22bc5715f6d1e5518f88b911d5ad5a4b86ee0cf29de308b4bca59eceb5adca5663d4b73

test:
  secret_key_base: a1c8c68a6c08bb8d02b85ae3b039001caeda3ba2ea00da77f69b98d211697b2afcad95b504e309ca030bd76004c45a6b3b7546d09ca5e42592ce4db52dd4dd65

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
